  name: UTILITIES-X
  main: linareslinares\Utilities
  version: 1.0
  api: 5.0.0
  author: "LinaresFunado [YT: @linareslinares]"
  description: "UTILITIES-X Proyecto hecho por LinaresFunado con el fin de unir varios plugins en uno solo y que sea util en servidores"

  commands:
    fly:
      permission: "fly.cmd"
      use: "/fly on off"

    ping:
      permission: "ping.cmd"
      use: "/ping"

    gm:
      permission: "gm.cmd"
      use: "/gm 0 1 3"

    hub:
      permission: "hub.cmd"
      use: "/hub"

    utils:
      permission: "utils.cmd"
      use: "/showutils"

    sethub:
      permission: "set.hub"
      use: "/sethub set <map>"

  permissions:
    cps.staff:
      default: op
    join.staff:
      default: op
    fly.cmd:
      default: op
    gm.cmd:
      default: op
    set.hub:
      default: op
    remove.hub:
      default: op
    hub.cmd:
      default: true
    ping.cmd:
      default: true
    utils.cmd:
      default: true
    diminuto.size:
      default: op
    pequeño.size:
      default: op
    grande.size:
      default: op
    enorme.size:
      default: op
    gigante.size:
      default: op
    custom.size:
      default: op
    cape.cmd:
      default: true
    Navidad.cape:
      default: true
    Turtle.cape:
      default: true
    Orange.cape:
      default: true
    Youtube.cape:
      default: op
    MiniYT.cape:
      default: op
    Discord.cape:
      default: op
    Fcito.cape:
      default: op
    Firework.cape:
      default: op
    Flowers Cian.cape:
      default: op
    Flowers Rose.cape:
      default: op
    Mario v1.cape:
      default: op
    hearts.cmd:
      default: op
    flame.cmd:
      default: op
    happy.cmd:
      default: op
    smoke.cmd:
      default: op
    snowball.cmd:
      default: op